### PR TITLE
Update Alpine version URL to fix Docker build

### PR DESCRIPTION
**Pull request by tannerhodges**
🙏 Hey @omerlh, thanks a ton for your [article](https://medium.com/soluto-engineering/testing-wordpress-plugins-can-be-fun-d926a20452b0) & this template. You've saved me some _major_ headaches trying to get unit testing setup for WordPress.

I had to make one small tweak to get the Docker build working, though.

This PR's pretty quick and sweet: simply updates the Alpine download to v3.7 instead of `edge` so that new folks can still get up and running without any errors.

| Before         | After          |
|----------------|----------------|
| Old edge version throws error during build | Updated v3.7 builds successfully |

Thanks again!

### CODE REVIEW

**Comment by omerlh** [comment]
Sure! Thank you and thank you for the kind words!

**Comment by omerlh** [comment]
Can you please fix the tests?

**Comment by tannerhodges** [comment]
Sorry, I'm not as familiar with debugging Docker…

It looks like the PHP 5.6 tests are failing but PHP 7.0 is passing.

PHP 5.6 builds are throwing this error:

```
ERROR: unsatisfiable constraints:
  musl-1.1.19-r10:
  breaks: musl-dev-1.1.19-r11[musl=1.1.19-r11]
```

Any ideas how I can resolve those constraints?

❓ Since PHP 5.6 has reached end of life, would it make sense to simply remove those tests and only keep the 7.0 builds?

**Comment by omerlh** [comment]
Yep, we can drop it - let's see if it helps!

**Comment by tannerhodges** [comment]
🙌 Looks like that did it!

Screen Shot 2021-02-18 at 9 14 59 AM

**Comment by omerlh** [comment]
Yay! Thank you so much!

**Pull request merged**
